# This play will be only be called if a new subnet has to be created for the tenant
# Steps to Execute
#   - Add MASQUERADE rules on the subnet router for the Tenant Network
---
- name: Init the octet list
  set_fact:
    octet_list: []
    sid: "{{item[1].split('#')[0]}}"
- debug:
    var: sid
- name: All the splitting
  vars:
    octet_list: []
  set_fact:
    octet_list: "{{ octet_list + [item[1].split('#')[1].split('.')[i]] }}"
  loop:
    - 0
    - 1
    - 2
  loop_control:
    loop_var: i

- name: Create the namespace
  command: ip netns add {{item[0].id}}{{sid}}

- name: Create bridge inside the namespace
  command: ip netns exec {{item[0].id}}{{sid}} brctl addbr {{item[0].id}}{{sid}}br

- name: Set the bridge to up
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev {{item[0].id}}{{sid}}br up

- name: Create a veth peer between SR and Tenant Network
  command: ip link add {{item[0].id}}sr-{{item[0].id}}{{sid}} type veth peer name {{item[0].id}}{{sid}}-{{item[0].id}}sr

- name: Add the veth peers to the corresponding namespace
  command: ip link set netns {{item[0].id}}sr dev {{item[0].id}}sr-{{item[0].id}}{{sid}}
  command: ip link set netns {{item[0].id}}{{sid}} dev {{item[0].id}}{{sid}}-{{item[0].id}}sr

- name: Give the veth peer between SR and Tenant Network IP addresses
  command: ip netns exec {{item[0].id}}sr ip addr add {{ vars[item[0].zone+'_TR']}}.1/30 dev {{item[0].id}}sr-{{item[0].id}}{{sid}}
  command: ip netns exec {{item[0].id}}{{sid}} ip addr add {{ vars[item[0].zone+'_TR']}}.2/30 dev {{item[0].id}}{{sid}}-{{item[0].id}}sr

- name: Enable the Interfaces
  command: ip netns exec {{item[0].id}}sr ip link set dev {{item[0].id}}sr-{{item[0].id}}{{sid}} up
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev {{item[0].id}}{{sid}}-{{item[0].id}}sr up

- name: Create Gateway veth pair
  command: ip netns exec {{item[0].id}}{{sid}} ip link add {{item[0].id}}{{sid}}-{{item[0].id}}{{sid}}br type veth peer name {{item[0].id}}{{sid}}br-{{item[0].id}}{{sid}}

- name: Enable the Gateway Interfaces
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev {{item[0].id}}{{sid}}-{{item[0].id}}{{sid}}br up
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev {{item[0].id}}{{sid}}br-{{item[0].id}}{{sid}} up

- name: Give the Gateway an IP
  command: ip netns exec {{item[0].id}}{{sid}} ip addr add {{octet_list[0]}}.{{octet_list[1]}}.{{octet_list[1]}}.{{ vars[item[0].zone+'_TR_subnet']}}/24 dev {{item[0].id}}{{sid}}-{{item[0].id}}{{sid}}br
  command: ip netns exec {{item[0].id}}{{sid}} brctl addif {{item[0].id}}{{sid}}br {{item[0].id}}{{sid}}br-{{item[0].id}}{{sid}}

- name: Add a VXLAN interface
  command: ip netns exec {{item[0].id}}{{sid}} ip link add vxlan0 type vxlan id 42 dev {{item[0].id}}{{sid}}-{{item[0].id}}sr remote 23.0.0.2 dstport 4789

- name: Set the VXLAN interface to up
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev vxlan0 up

- name: Add the VXLAN to the bridge
  command: ip netns exec {{item[0].id}}{{sid}} brctl addif {{item[0].id}}{{sid}}br vxlan0

- name: Update FDB table
  command: ip netns exec {{item[0].id}}{{sid}} bridge fdb append 00:00:00:00:00:00 dst 23.0.0.2 dev vxlan0

- name: Add the ip routes
  command: ip netns exec {{item[0].id}}{{sid}} ip route add default via 22.0.0.1 dev {{item[0].id}}{{sid}}-{{item[0].id}}sr
