# This play will be only be called if a new subnet has to be created for the tenant
---
- name: Init the octet list
  set_fact:
    octet_list: []
    sid: "{{item[1].split('#')[0]}}"
    
- name: All the splitting
  vars:
    octet_list: []
  set_fact:
    octet_list: "{{ octet_list + [item[1].split('#')[1].split('.')[i]] }}"
  loop:
    - 0
    - 1
    - 2
  loop_control:
    loop_var: i

- name: Create the namespace
  command: ip netns add {{item[0].id}}{{sid}}

- name: Create bridge inside the namespace
  command: ip netns exec {{item[0].id}}{{sid}} brctl addbr {{item[0].id}}{{sid}}br

- name: Set the bridge to up
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev {{item[0].id}}{{sid}}br up

- name: Create a veth peer between SR and Tenant Network
  command: ip link add {{item[0].id}}sr-{{item[0].id}}{{sid}} type veth peer name {{item[0].id}}{{sid}}-{{item[0].id}}sr

- name: Add the interface to SR namespace
  command: ip link set netns {{item[0].id}}sr dev {{item[0].id}}sr-{{item[0].id}}{{sid}}

- name: Add interface to Tenant namespace
  command: ip link set netns {{item[0].id}}{{sid}} dev {{item[0].id}}{{sid}}-{{item[0].id}}sr

# Subsequent runs start

- name: Get file content
  command: cat ./roles/create_tenant_ns/tasks/counter.yml
  register: oldcounter

- name: Update counter 1
  local_action: shell temp=$((`cat ./roles/create_tenant_ns/tasks/counter.yml` + 3)); echo $temp
  register: newcounter1

- name: Give the veth peer between SR and Tenant Network IP addresses
  command: ip netns exec {{item[0].id}}sr ip addr add {{ vars[item[0].zone+'_TR']}}.{{newcounter1.stdout}}/30 dev {{item[0].id}}sr-{{item[0].id}}{{sid}}

# Update the Counter again

- name: Update counter 2
  local_action: shell temp=$((`cat ./roles/create_tenant_ns/tasks/counter.yml` + 4)); echo $temp
  register: newcounter2

- name: Give the veth peer between Tenant Network and SR IP addresses
  command: ip netns exec {{item[0].id}}{{sid}} ip addr add {{ vars[item[0].zone+'_TR']}}.{{newcounter2.stdout}}/30 dev {{item[0].id}}{{sid}}-{{item[0].id}}sr

- name: Enable the Interface between SR and TN
  command: ip netns exec {{item[0].id}}sr ip link set dev {{item[0].id}}sr-{{item[0].id}}{{sid}} up

- name: Enable the Interface between TN and SR
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev {{item[0].id}}{{sid}}-{{item[0].id}}sr up

- name: Create Gateway veth pair
  command: ip netns exec {{item[0].id}}{{sid}} ip link add {{item[0].id}}{{sid}}-{{item[0].id}}{{sid}}br type veth peer name {{item[0].id}}{{sid}}br-{{item[0].id}}{{sid}}

- name: Enable the Gateway Interface on the TN
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev {{item[0].id}}{{sid}}-{{item[0].id}}{{sid}}br up

- name: Enable the Gateway Interface on the Bridge
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev {{item[0].id}}{{sid}}br-{{item[0].id}}{{sid}} up

- name: Give the Gateway an IP
  command: ip netns exec {{item[0].id}}{{sid}} ip addr add {{octet_list[0]}}.{{octet_list[1]}}.{{octet_list[1]}}.{{ vars[item[0].zone+'_TR_subnet']}}/24 dev {{item[0].id}}{{sid}}-{{item[0].id}}{{sid}}br
  
- name: Add the Gateway interface to the Bridge
  command: ip netns exec {{item[0].id}}{{sid}} brctl addif {{item[0].id}}{{sid}}br {{item[0].id}}{{sid}}br-{{item[0].id}}{{sid}}

- name: Add a VXLAN interface
  command: ip netns exec {{item[0].id}}{{sid}} ip link add vxlan0 type vxlan id 42 dev {{item[0].id}}{{sid}}-{{item[0].id}}sr remote 23.0.0.2 dstport 4789

- name: Set the VXLAN interface to up
  command: ip netns exec {{item[0].id}}{{sid}} ip link set dev vxlan0 up

- name: Add the VXLAN to the bridge
  command: ip netns exec {{item[0].id}}{{sid}} brctl addif {{item[0].id}}{{sid}}br vxlan0

- name: Update FDB table
  command: ip netns exec {{item[0].id}}{{sid}} bridge fdb append 00:00:00:00:00:00 dst 23.0.0.2 dev vxlan0

- name: Add the ip routes
  command: ip netns exec {{item[0].id}}{{sid}} ip route add default via {{ vars[item[0].zone+'_TR']}}.{{newcounter1.stdout}} dev {{item[0].id}}{{sid}}-{{item[0].id}}sr

- name: Updating counter file
  copy:
    content: "{{ newcounter2.stdout}}"
    dest: "./roles/create_tenant_ns/tasks/counter.yml"
