# This play will be only be called if a new subnet has to be created for the tenant
# Steps to Execute
#   - Add MASQUERADE rules on the subnet router for the Tenant Network
---
- name: Create the namespace
  command: ip netns add {{item[0].id}}{{item[1]}}
- name: Create bridge inside the namespace
  command: ip netns exec {{item[0].id}}{{item[1]}} brctl addbr {{item[0].id}}{{item[1]}}br
- name: Set the bridge to up
  command: ip netns exec {{item[0].id}}{{item[1]}} ip link set dev {{item[0].id}}{{item[1]}}br up
- name: Create a veth peer between SR and Tenant Network
  command: ip link add {{item[0].id}}sr-{{item[0].id}}{{item[1]}} type veth peer name {{item[0].id}}{{item[1]}}-{{item[0].id}}sr
- name: Add the veth peers to the corresponding namespace
  command: ip link set netns {{item[0].id}}sr dev {{item[0].id}}sr-{{item[0].id}}{{item[1]}}
  command: ip link set netns {{item[0].id}}{{item[1]}} dev {{item[0].id}}{{item[1]}}-{{item[0].id}}sr
- name: Give the veth peer between SR and Tenant Network IP addresses
  command: ip netns exec {{item[0].id}}sr ip addr add 22.0.0.x/30 dev {{item[0].id}}sr-{{item[0].id}}{{item[1]}}
  command: ip netns exec {{item[0].id}}{{item[1]}} ip addr add 22.0.0.x+1/30 dev {{item[0].id}}{{item[1]}}-{{item[0].id}}sr
- name: Create Gateway veth pair
  command: ip netns exec ip link add {{item[0].id}}{{item[1]}}-{{item[0].id}}{{item[1]}}br type veth peer name {{item[0].id}}{{item[1]}}br-{{item[0].id}}{{item[1]}}
- name: Give the Gateway an IP
  command: ip netns exec {{item[0].id}}{{item[1]}} ip addr add subnet.1|254/24 dev {{item[0].id}}{{item[1]}}-{{item[0].id}}{{item[1]}}br
- name: Add a VXLAN interface
  command: ip netns exec {{item[0].id}}{{item[1]}} ip link add vxlan0 type vxlan id 42 dev {{item[0].id}}_vxlan remote 23.0.0.x dstport 4789
- name: Set the VXLAN interface to up
  command: ip netns exec {{item[0].id}}{{item[1]}} ip link set dev vxlan0 up
- name: Add the VXLAN to the bridge
  command: ip netns exec {{item[0].id}}{{item[1]}} brctl addif {{item[0].id}}{{item[1]}}br vxlan0
- name: Update FDB table
  command: ip netns exec {{item[0].id}}{{item[1]}} bridge fdb append 00:00:00:00:00:00 dst 23.0.0.x dev vxlan0
- name: Add the ip routes
  command: ip netns exec {{item[0].id}}{{item[1]}} ip route add default via 22.0.0.1 dev {{item[0].id}}{{item[1]}}-{{item[0].id}}sr
