---
- hosts: zones
  user: root
  become_method: sudo
  become: yes
  tasks:
  - name: Add the iptables rule on the Subnet router
    shell: |
      ip netns exec {{ item }} iptables -F INPUT
      ip netns exec {{ item }} iptables -A INPUT -p tcp -m comment --comment "TRAFFIC" -j ACCEPT
    with_items: "{{ netns_name }}"
  - name:
    copy:
      src: "{{ router_sh }}"
      dest: /home/ece792/router_logging/
      
  - name: Setup cron to monitor the tenant router
    cron:
      job: "sh /home/ece792/router_logging/{{ router_sh }} >/dev/null 2>&1"
      
