---
- hosts: tenant_vms
  user: root
  become_method: sudo
  become: yes
  tasks:
  - name: Copy the collectd.conf
    copy:
      src: "{{ item }}"
      dest: /etc/collectd/collectd.conf
      owner: root
      mode: '0644'
    with_items:
      - "{{ collectd_file }}"
  
  - name: Copy the custom script
    copy:
      src: "{{ custom_file }}"
      dest: /opt/custom_plugins/
    when: custom_file != "None"
 
  - name: Cron to setup custom logging
    cron:
      name: Seting up the custom logging
      job: "python /opt/custom_plugins/data.py > /dev/null 2>&1"
      minutes: 1
    when: custom_file != "None"

  - name: Restarting Collectd on the VM
    service:
      name: collectd
      state: restarted
