---
- hosts: tenant_vms
  user: root
  become_method: sudo
  become: yes
  tasks:
  - name: Copy the collectd.conf
    copy:
      src: "{{ item }}"
      dest: /etc/collectd.conf
      owner: root
      mode: '0644'
    with_items:
      - "{{ collectd_file }}"
  
  - name: Copy the custom script
    copy:
      src: "{{ custom_file }}"
      dest: /opt/custom_plugins/
    when: custom_file != "None"
  
  - name: Restarting Collectd on the VM
    systemd:
      name: collectd
      state: restarted
