---
- hosts: "{{host}}"
  user: root
  become: yes
  
  tasks:
  - pip:
      name: docker
      state: latest

  - name: Spawn the container
    docker_container:
      name: "{{ vmid }}"
      image: maas/client
      command: bash
      state: started
      interactive: yes
      detach: yes
      recreate: yes

  - name: Start SSH
    command: docker exec  "{{ vmid }}" service ssh start
