# # config file version
apiVersion: 1


# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
#   # <string, required> name of the datasource. Required
 - name: MyDB
#   # <string, required> datasource type. Required
   type: influxdb
#   # <string, required> access mode. direct or proxy. Required
   access: direct
#   # <int> org id. will default to orgId 1 if not specified
#   orgId: 1
#   # <string> url
   url: http://localhost:8086
#   # <string> database password, if used
#   password:
#   # <string> database user, if used
#   user:
#   # <string> database name, if used
   database: collectd
#   # <bool> enable/disable basic auth
#   basicAuth:
#   # <string> basic auth username
#   basicAuthUser:
#   # <string> basic auth password
#   basicAuthPassword:
   editable: true