---
- name: Install OVS
  package:
    name: openvswitch-switch
    state: present
- name: Install Libguestfs
  package:
    name: libguestfs-tools
    state: present
- name: Create OVS Switch
  - openvswitch_bridge:
    bridge: "{{item[0].id}}{{vm#}}br"
    state: present
- name: Create network.xml for the OVS Bridge
  copy:
    dest: "/etc/libvirt/qemu/networks/net_{{item[0].id}}{{vm#}}.xml"
    content: |
      <network>
        <name>{{item[0].id}}{{vm#}}net</name>
        <bridge name= '{{item[0].id}}{{vm#}}br'/>
        <virtualport type='openvswitch'/>
        <forward mode="bridge"/>
      </network>
- name: Define the Network
  - virt_net:
      command: define
      name: "{{item[0].id}}{{vm#}}net"
      xml: '/etc/libvirt/qemu/networks/net_{{item[0].id}}{{vm#}}.xml'
- name: Start the Network 
  - virt_net:
      state: active
      name: "{{item[0].id}}{{vm#}}br"
- name: Spawn the VM Image
  command: virt-builder centos-7.0 --root-password password:root -o {{item[0].id}}{{vm#}}.img --size 10G --update --firstboot-command 'dhclient eth0'
- name: Install the VM
  command: virt-install --name {{item[0].id}}{{vm#}} --ram 2048 --disk-path={{item[0].id}}{{vm#}}.img --os-type linux --os-variant rhel7.5 --import


