---
- name: Install OVS
  package:
    name: openvswitch-switch
    state: present
- name: Install Libguestfs
  package:
    name: libguestfs-tools
    state: present
- name: Create OVS Switch
  - openvswitch_bridge:
    bridge: "{{item[0].id}}{{vm#}}br"
    state: present
- name: Create network.xml for the OVS Bridge
  copy:
    dest: "/etc/libvirt/qemu/networks/net_{{item[0].id}}{{vm#}}.xml"
    content: |
      <network>
        <name>{{item[0].id}}{{vm#}}net</name>
        <bridge name= '{{item[0].id}}{{vm#}}br'/>
        <virtualport type='openvswitch'/>
        <forward mode="bridge"/>
      </network>
- name: Define the Network
  - virt_net:
      command: define
      name: "{{item[0].id}}{{vm#}}net"
      xml: '/etc/libvirt/qemu/networks/net_{{item[0].id}}{{vm#}}.xml'
- name: Start the Network 
  - virt_net:
      state: active
      name: "{{item[0].id}}{{vm#}}br"
- name: Spawn the VM Image
  command: sudo virt-builder centos-7.0 --root-password password:root -o {{item[0].id}}{{vm#}}.img --size 10G --attach <Centos iso>
  environment:
    LIBGUESTFS_BACKEND: 'direct'
- name: Install the VM
  command: virt-install -n {{item[0].id}}{{vm#}} --memory 2048 --vcpus 2 --disk {{item[0].id}}{{vm#}}.img --boot hd --os-variant rhel7 --import --noautoconsole
- name: Attach Interface to VM
  command: sudo virsh attach-interface --domain {{item[0].id}}{{vm#}} --type network --source {{item[0].id}}{{vm#}}net --model virtio --config --live
- name: Create interface between bridge and namespace
  command: ip link add {{item[0].id}}{{vm#}}br-{{item[0].id}}{{item[1]}} type veth peer name {{item[0].id}}{{item[1]}}-{{item[0].id}}{{vm#}}br
- name: Connect Interface to bridge
  command: ovs-vsctl add-if {{item[0].id}}{{vm#}}br {{item[0].id}}{{vm#}}br-{{item[0].id}}{{item[1]}}
- name: Connect Interface to Tenant Router
  command: ip link set netns {{item[0].id}}{{item[1]}} dev {{item[0].id}}{{item[1]}}-{{item[0].id}}{{vm#}}br
  command: ip netns exec {{item[0].id}}{{item[1]}} brctl addif {{item[0].id}}{{item[1]}}br {{item[0].id}}{{item[1]}}-{{item[0].id}}{{vm#}}br


