FROM philhawthorne/docker-influxdb-grafana:latest

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y --no-install-recommends --no-install-suggests install iproute2
RUN apt-get -y --no-install-recommends --no-install-suggests install openssh-server
RUN apt-get -y --no-install-recommends --no-install-suggests install iptables
RUN apt-get -y --no-install-recommends --no-install-suggests install iputils-ping
RUN apt-get -y --no-install-recommends --no-install-suggests install nano
RUN apt-get -y --no-install-recommends --no-install-suggests install tcpdump
RUN apt-get -y --no-install-recommends --no-install-suggests install influxdb
RUN apt-get -y --no-install-recommends --no-install-suggests install keepalived

ADD grafana.ini /root/collect_capture.py
ADD datasources.yaml /etc/grafana/provisioning/datasources/datasources.yaml
ADD influxdb.conf /etc/influxdb/influxdb.conf
ADD types.db /usr/local/share/collectd/types.db
ADD sshd_config /etc/ssh/sshd_config
