FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y --force-yes install iproute2
RUN apt-get -y --force-yes install openssh-server
RUN apt-get -y --force-yes install iptables
RUN apt-get -y --force-yes install iputils-ping
RUN apt-get -y --force-yes install vim
RUN apt-get -y --force-yes install tcpdump
RUN apt-get -y --force-yes install influxdb
RUN apt-get -y --force-yes install keepalived

RUN wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
RUN apt-get update
RUN apt-get -y --force-yes install grafana

ADD grafana.ini /root/collect_capture.py
ADD datasources.yaml /etc/grafana/provisioning/datasources/datasources.yaml
ADD influxdb.conf /etc/influxdb/influxdb.conf
ADD types.db /usr/local/share/collectd/types.db

RUN systemctl start grafana-server
RUN systemctl start influxd

RUN dhclient
