---
- hosts: zone
  user: root
  become: yes
  tasks:
  - name: Attach the interface
    shell: virsh attach-interface --domain {{vmid}} --type network --source {{network_name}} --model virtio --config --live
    # when: "'172.16.3.1' in ansible_all_ipv4_addresses'" or "'172.16.3.2' in ansible_all_ipv4_addresses'"

- hosts: tenant_vms
  user: root
  become: yes
  tasks:
  - name: Set the interface to up
    shell: ip link set dev {{dev_name}} up
  - name: Add the IP
    shell: ip addr add {{ip_addr}}/25 dev {{dev_name}}
    # when: "'172.16.3.1' not in ansible_all_ipv4_addresses'" or "'172.16.3.2' not in ansible_all_ipv4_addresses'"
  - name: Add default route if it is the first subnet in the list
    shell: "{{ item }}"
    with_items:
      - "ip route del default"
      - "ip route add default dev '{{dev_name}}' via '{{gw_ip}}'"
    when: flag == "True"
  - name: Add iptable rules for tenant Isolation
    shell: "{{ item }}"
    with_items:
      - iptables -I OUTPUT -d {{ virtual_ip }} -j ACCEPT
      - iptables -I OUTPUT -d {{ virtual_ip }} -p tcp --dport 22 -j REJECT
      - iptables -I OUTPUT -d 192.168.123.0/24 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      - iptables -A OUTPUT -d 192.168.123.0/24 -j REJECT
