FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y --force-yes install iproute2
RUN apt-get -y --force-yes install openssh-server
RUN apt-get -y --force-yes install iptables
RUN apt-get -y --force-yes install iputils-ping
RUN apt-get -y --force-yes install vim
RUN apt-get -y --force-yes install tcpdump
RUN apt-get -y --force-yes install collectd

RUN systemctl start collectd

RUN dhclient
