---
- hosts: all
  user: root
  become: yes
  
  tasks:
  - name: Clone the VM
    command: virt-clone --original {{image}} --name {{vmid}} --auto-clone

  - name: Start the VM 
    command: virsh start {{vmid}}
  
  - name: Fetching IP address using dhclient
    pause:
      seconds: 35
  
  - name: Setup cron job
    cron:
      name: collectd
      job: "uptime | awk '{print $8 $9 $10}' > /opt/custom_plugins/data.txt"
      minute: "1"